PetShop/Models/Order.cs
using System;
using System.Collections.Generic;

namespace PetShop.Models
{
    public partial class Order
    {
        public Order()
        {
            OrderDetails = new HashSet<OrderDetail>();
            ReasonCancels = new HashSet<ReasonCancel>();
            Ships = new HashSet<Ship>();
        }

        public int OrderId { get; set; }
        public string CustomerId { get; set; } = null!;
        public string? EmployeeId { get; set; }
        public DateTime? OrderDate { get; set; }
        public DateTime? ShippedDate { get; set; }
        public string? OrderStatus { get; set; }

        public virtual Customer Customer { get; set; } = null!;
        public virtual Employee? Employee { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<ReasonCancel> ReasonCancels { get; set; }
        public virtual ICollection<Ship> Ships { get; set; }
    }
}

PetShop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PetShop.Models;
using System.Text.Json;
using static PetShop.Controllers.ProductController;

namespace PetShop.Controllers
{
    public class OrderController : Controller
    {
        private readonly ProjectContext _db;
        private readonly IVnPayService _vpnPayService;

        public OrderController(ProjectContext db, IVnPayService vnPayService)
        {
            _vpnPayService = vnPayService;
            _db = db;
        }



        public IActionResult AddToCart(int id, decimal unitPrice)
        {
            List<OrderDetail> orderList = new List<OrderDetail>();


            if (HttpContext.Session.GetString("order") != null)
            {
                string data = HttpContext.Session.GetString("order");
                orderList = JsonSerializer.Deserialize<List<OrderDetail>>(data);
            }
            else
            {
                orderList = new List<OrderDetail>();
            }

            OrderDetail order = orderList.FirstOrDefault(s => s.ProductId == id);
            if (order != null)
            {
                order.Quantity++;
            }
            else
            {
                order = new OrderDetail();
                order.ProductId = id;
                order.Quantity = 1;
                order.UnitPrice = unitPrice;
                orderList.Add(order);
            }



            int totalUniqueProductIds = orderList.Select(item => item.ProductId).Distinct().Count();
            HttpContext.Session.SetInt32("NumOfCartItems", totalUniqueProductIds);
            HttpContext.Session.SetString("order", JsonSerializer.Serialize(orderList));
            return RedirectToAction("ListProduct", "Product");
        }

        public IActionResult ViewOrder()
        {
            List<OrderDetail> list = new List<OrderDetail>();
            List<CategoryProductModel> CategoryProducts = new List<CategoryProductModel>();
            if (HttpContext.Session.GetString("order") != null)
            {
                string data = HttpContext.Session.GetString("order");
                list = JsonSerializer.Deserialize<List<OrderDetail>>(data);
            }
            else
            {
                list = new List<OrderDetail>();
            }

            list.ForEach(
                x =>
                {
                    x.Product = _db.Products.Include(s => s.Pictures).FirstOrDefault(b => b.ProductId == x.ProductId);
                }

                );
            CategoryProducts.Add(new CategoryProductModel
            {
                OrderDetails = list
            });

            return View(CategoryProducts);
        }

        public IActionResult DeleteToCard(int id)
        {
            List<OrderDetail> list = new List<OrderDetail>();
            if (HttpContext.Session.GetString("order") != null)
            {
                string data = HttpContext.Session.GetString("order");
                list = JsonSerializer.Deserialize<List<OrderDetail>>(data);

                var itemToRemove = list.FirstOrDefault(x => x.ProductId == id);
                if (itemToRemove != null)
                {
                    list.Remove(itemToRemove);
                    int totalUniqueProductIds = list.Select(item => item.ProductId).Distinct().Count();
                    HttpContext.Session.SetInt32("NumOfCartItems", totalUniqueProductIds);
                }

                HttpContext.Session.SetString("order", JsonSerializer.Serialize(list));
            }

            return RedirectToAction("ViewOrder");
        }


        public IActionResult DeleteToCart(int id)
        {
            List<OrderDetail> list = new List<OrderDetail>();
            if (HttpContext.Session.GetString("order") != null)
            {
                string data = HttpContext.Session.GetString("order");
                list = JsonSerializer.Deserialize<List<OrderDetail>>(data);

                var itemToRemove = list.FirstOrDefault(x => x.ProductId == id);
                if (itemToRemove != null)
                {
                    list.Remove(itemToRemove);
                    int totalUniqueProductIds = list.Select(item => item.ProductId).Distinct().Count();
                    HttpContext.Session.SetInt32("NumOfCartItems", totalUniqueProductIds);
                }

                HttpContext.Session.SetString("order", JsonSerializer.Serialize(list));
            }

            return RedirectToAction("ListProduct", "Product");
        }

        public IActionResult Payment(List<OrderDetail> orderDetails, string payment)
        {
            if (!User.Identity.IsAuthenticated)
            {
                string mess = "You must be logged in to proceed. Please log in!";
                HttpContext.Session.SetString("messFail", mess);
                return RedirectToAction("SignIn", "Home");
            }
            else if (payment.Contains("Payment"))
            {
                string acc = HttpContext.Session.GetString("LoggedInAccount");
                Account account = JsonSerializer.Deserialize<Account>(acc);
                if (account != null)
                {
                    List<OrderDetail> list = new List<OrderDetail>();
                    string data = HttpContext.Session.GetString("order");
                    list = JsonSerializer.Deserialize<List<OrderDetail>>(data);

                    double total = 0;

                    foreach (OrderDetail item in list)
                    {
                        total += (double)(item.Quantity * item.UnitPrice);
                    }

                    //Order order = new Order()
                    //{
                    //    CustomerId = account.CustomerId,
                    //    EmployeeId = account.EmployeeId,
                    //    OrderDate = DateTime.Now,
                    //    ShippedDate = DateTime.Now,
                    //    OrderStatus = "Delivered"
                    //};
                    //_db.Orders.Add(order);
                    //_db.SaveChanges();

                    //int latestOrderId = _db.Orders.Max(o => (int?)o.OrderId) ?? 0;

                    //foreach (var orderDetail in orderDetails)
                    //{
                    //    orderDetail.OrderId = latestOrderId;
                    //    orderDetail.UnitPrice = orderDetail.Quantity * orderDetail.UnitPrice;
                    //    _db.OrderDetails.Add(orderDetail);
                    //}
                    //_db.SaveChanges();

                    //double totalPrice = 0;
                    //foreach (var orderDetail in orderDetails)
                    //{
                    //    totalPrice += (double)(orderDetail.Quantity * orderDetail.UnitPrice);
                    //}

                    var vnpayModel = new VnPaymentRequestModel
                    {
                        Amount = total,
                        CreatedDate = DateTime.Now
                    };
                    //delete session after add
                    //int idDelete = 0;
                    //foreach (var orderDetail in orderDetails)
                    //{
                    //    idDelete = orderDetail.ProductId;

                    //}
                    //List<OrderDetail> list = new List<OrderDetail>();
                    //if (HttpContext.Session.GetString("order") != null)
                    //{
                    //    string data = HttpContext.Session.GetString("order");
                    //    list = JsonSerializer.Deserialize<List<OrderDetail>>(data);

                    //    var itemToRemove = list.FirstOrDefault(x => x.ProductId == idDelete);
                    //    if (itemToRemove != null)
                    //    {
                    //        list.Remove(itemToRemove);
                    //        int totalUniqueProductIds = list.Select(item => item.ProductId).Distinct().Count();
                    //        HttpContext.Session.SetInt32("NumOfCartItems", totalUniqueProductIds);
                    //    }

                    //    HttpContext.Session.SetString("order", JsonSerializer.Serialize(list));
                    //}

                    return Redirect(_vpnPayService.CreatePaymentUrl(HttpContext, vnpayModel));
                }
            }
            return Ok();
        }

        public IActionResult PaymentFail()
        {
            string mess = "You has must been loginn!!. Please Login!!";
            HttpContext.Session.SetString("messFail", mess);
            return RedirectToAction("ListProduct", "Product");
        }
        public IActionResult PaymentBack()
        {
            var response = _vpnPayService.PaymentExecute(Request.Query);

            if (response == null || response.VnPayResponseCode != "00")
            {
                TempData["Message"] = $"Payment Fail!!: {response.VnPayResponseCode}";


                return RedirectToAction("PaymentFail");
            }

            if (!User.Identity.IsAuthenticated)
            {
                string messT = "You must be logged in to proceed. Please log in!";
                HttpContext.Session.SetString("messFail", messT);
                return RedirectToAction("SignIn", "Home");
            }
            else
            {
                string acc = HttpContext.Session.GetString("LoggedInAccount");
                Account account = JsonSerializer.Deserialize<Account>(acc);
                if (account != null)
                {
                    List<OrderDetail> list = new List<OrderDetail>();
                    string data = HttpContext.Session.GetString("order");
                    list = JsonSerializer.Deserialize<List<OrderDetail>>(data);

                    Order order = new Order()
                    {
                        CustomerId = account.CustomerId,
                        EmployeeId = account.EmployeeId,

PetShop/Views/Order/ViewOrder.cshtml
@model List<PetShop.Controllers.ProductController.CategoryProductModel>



@{
    ViewData["Title"] = "View Order";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="h-100" style="background-color: #eee;">
    <div class="container h-100 py-5">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-10">

                <div class="d-flex justify-content-between align-items-center mb-4">
                    <h3 class="fw-normal mb-0 text-black">Shopping Cart</h3>
                    <div>
                        <p class="mb-0">
                            <span class="text-muted">Sort by:</span> <a href="#!" class="text-body">
                                price <i class="fas fa-angle-down mt-1"></i>
                            </a>
                        </p>
                    </div>
                </div>
                <form asp-controller="Order" asp-action="Payment" method="post">
                    @foreach (var categoryProduct in Model)
                    {
                        if (categoryProduct.OrderDetails != null && categoryProduct.OrderDetails.Any())
                        {
                            foreach (var orderDetail in categoryProduct.OrderDetails)
                            {
                                <div class="card rounded-3 mb-4">
                                    <div class="card-body p-4">
                                        <div class="row d-flex justify-content-between align-items-center">
                                            <div class="col-md-2 col-lg-2 col-xl-2">
                                                <img class="img-fluid rounded-3" src="@orderDetail.Product.Pictures.FirstOrDefault()?.Picture" alt="Product Image">
                                            </div>
                                            <div class="col-md-3 col-lg-3 col-xl-3">
                                                <p class="lead fw-normal mb-2">@orderDetail.Product.ProductName</p>
                                                <input type="hidden" name="orderDetails[@Model.IndexOf(categoryProduct)].ProductId" value="@orderDetail.ProductId" />
                                            </div>
                                            <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                                                <input id="quantityInput_@orderDetail.ProductId"
                                                       min="1" name="orderDetails[@Model.IndexOf(categoryProduct)].Quantity"
                                                       value="@orderDetail.Quantity" type="number" class="form-control form-control-sm quantity-input"
             x                                          data-product-id="@orderDetail.ProductId" />
                                            </div>
                                            <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                                <h5 class="mb-0 subtotal" id="subtotal_@orderDetail.ProductId" data-unit-price="@orderDetail.Product.UnitPrice">$@(orderDetail.Product.UnitPrice * orderDetail.Quantity)</h5>
                                                <input type="hidden" name="orderDetails[@Model.IndexOf(categoryProduct)].UnitPrice" value="@orderDetail.Product.UnitPrice" />
                                            </div>
                                            <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                                                <a asp-action="DeleteToCard" asp-controller="Order" asp-route-id="@orderDetail.ProductId" class="text-danger">
                                                    <i class="fas fa-trash fa-lg"></i>
                                                </a>
                                            </div>
                                            
                                        </div>
                                    </div>
                                </div>
                            }
                        }
                    }

                    <div class="col-md-1 col-lg-5 text-end">
                        <input type="submit" name="payment" class="btn btn-warning btn-block btn-lg" value="Payment" />
                    </div>
                </form>


            </div>
        </div>
    </div>
</section>